name: Update Hugging Face repository
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face
        env:
          HF_USER: ${{ secrets.HF_USER }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://${{ secrets.HF_USER }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USER }}/tess-pointing-checker main --force
